### ISSUE TITLE
Cannot call `SwapDeployer::LPResourceAccount::initialize_lp_account`

### ISSUE THREAD

**Issue by SamTop-Solicy** [AnimeSwap/v1-core#14]
When I try to call the function with a command like this `aptos move run --function-id SwapDeployer::LPResourceAccount::initialize_lp_account --args hex:SomeHexVal hex:AnotherHexVal --profile SwapDeployer` I get an error: `MODULE_ADDRESS_DOES_NOT_MATCH_SENDER`. In the codes I found that resource account is created from the signer and that is passed to `publish_package_txn()`.

**Comment by SamTop-Solicy** [comment]
Solved it. Needed to construct `ResourceAccountDeployer` address from `SwapDeployer`.

**Comment by FISTdao** [comment]
> Solved it. Needed to construct `ResourceAccountDeployer` address from `SwapDeployer`.

How should I build ResourceAccountDeployer？thanks
