### ISSUE TITLE
local U256 & UQ64x64 are conflicting with other packages

### ISSUE THREAD

**Issue by UglyTroLL** [AnimeSwap/v1-core#15]
AnimeSwap is using local U256 / UQ64x64 deps, which is conflicting with other U256/UQ64x64 deps from github in other packages.
Can we make U256 / UQ64x64 deps from github instead of local deps?

**Comment by UglyTroLL** [comment]
Compiling error msg: 
```  "Error": "Move compilation failed: Unable to resolve packages for package 'xxx': While resolving dependency 'yyyy' in package 'xxx': Unable to resolve package dependency 'yyyy': While resolving dependency 'U256' in package 'yyyy': Unable to resolve package dependency 'U256': Conflicting dependencies found: package 'U256' conflicts with 'U256'```

**Comment by foolstack-omg** [comment]
I have the same problem

**Comment by hexiaoyuan** [comment]
same+1

**Comment by xiaozzz** [comment]
https://github.com/hippospace/hippo-aggregator/tree/main/interface/animeswap
Maybe you can refer to this, just write the interface, that is the public functions you need.
