### ISSUE TITLE
Aptos framewokr's rev 83641d3f083762f31700060e5e95fbb1cbc28bf0 isn't exist anymore.

### ISSUE THREAD

**Issue by foolstack-omg** [AnimeSwap/v1-core#16]
When I use AnimeSwap as a dependency, the console can't download aptos framework because rev "83641d3f083762f31700060e5e95fbb1cbc28bf0" can't be found.

**Comment by FISTdao** [comment]
> When I use AnimeSwap as a dependency, the console can't download aptos framework because rev "83641d3f083762f31700060e5e95fbb1cbc28bf0" can't be found.

can be downloaded,If you are in mainland China, please use a VPN to ensure smooth network
Below is my deployment：
https://explorer.aptoslabs.com/account/0x486aad295334103cecae9bcad86c025d3dc3af1f41902083e1dd5d09026beb59/modules

**Comment by FISTdao** [comment]
> When I use AnimeSwap as a dependency, the console can't download aptos framework because rev "83641d3f083762f31700060e5e95fbb1cbc28bf0" can't be found.

But i want to know how to get ResourceAccountDeployer, if you know please help me

**Comment by xiaozzz** [comment]
https://github.com/aptos-labs/aptos-core/commit/83641d3f083762f31700060e5e95fbb1cbc28bf0
use VPN
