### ISSUE TITLE
`public entry fun` We could now to use u128/u256 directly on entry functions.

### ISSUE THREAD

**Issue by ghost** [AnimeSwap/v1-core#23]
https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/aptos-vm/src/verifier/transaction_arg_validation.rs

**Comment by xiaozzz** [comment]
New Integer Types (u16, u32, u256) is added to devnet and testnet, but not mainnet.
https://discord.com/channels/945856774056083548/956692649430093904/1051938346127069184
btw, no need for upgrading this u256. Out contract does not use this type in almost all txs. u256 is only used in some extreme cases which may be never triggered.

**Comment by ghost** [comment]
> New Integer Types (u16, u32, u256) is added to devnet and testnet, but not mainnet. https://discord.com/channels/945856774056083548/956692649430093904/1051938346127069184 btw, no need for upgrading this u256. Out contract does not use this type in almost all txs. u256 is only used in some extreme cases which may be never triggered.

no, its for gas optimizing reason, one less cast, next txn will has less gas cost.
Gas cost table:
https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/aptos-gas/src/instr.rs

**Comment by xiaozzz** [comment]
> 

as i told here, user tx should never use type u256, so it will not save any user's gas. This part is already gas-optimized in our code.
https://github.com/AnimeSwap/v1-core/blob/main/Swap/sources/swap.move#L329
https://github.com/AnimeSwap/v1-core/blob/main/Swap/sources/swap.move#L386
It only saves contract deployer gas.

**Comment by xiaozzz** [comment]
if you can show some detailed codes for gas optimizing, i will reopen this issue and fix it

**Comment by ghost** [comment]
> if you can show some detailed codes for gas optimizing, i will reopen this issue and fix it

Let me show you a trick about how to optimize gas cost fee down:
https://explorer.aptoslabs.com/txn/0xe57f3b70dd563be6c4b760192e7723049bab26ab4edb9b5065fef24f6868831a/payload 
This txn is on the Devnet.

```
    public entry fun s0t1<A, B> (
        a: u128, u_u128: u128, u_u64: u64,
        a1: u128, b2: u128,
        c3: u128, d4: u128,
        ar: u128, br:u128, aa: bool, bb: bool,
        zero_u64: u64, zero_u128: u128
    ) {}
```

if try to execute entry function from entry, any parameter are zero cost except txn size cost.

and pls try to inline any private function, that could also do gas cost optimize up.
